name = "CATHBase"
uuid = "5a9067f6-bd04-11e9-2b5e-0b0ddcaa54f0"
authors = ["harryscholes"]
version = "0.1.0"

[compat]
julia = "1.1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
